services:
    email.email:
        class: Librinfo\EmailBundle\Admin\EmailAdminConcrete
        arguments: [~, Librinfo\EmailBundle\Entity\Email, LibrinfoEmailBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Email }
        calls:
            - [ setTemplate, [edit, LibrinfoEmailBundle:CRUD:email_edit.html.twig]]

    email.email_attachment:
        class: Librinfo\EmailBundle\Admin\EmailAttachmentAdminConcrete
        arguments: [~, Librinfo\EmailBundle\Entity\EmailAttachment, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: EmailAttachment }

    email.email_template:
        class: Librinfo\EmailBundle\Admin\EmailTemplateAdminConcrete
        arguments: [~, Librinfo\EmailBundle\Entity\EmailTemplate, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: EmailTemplate }
        calls:
            - [ setTemplate, [edit, LibrinfoEmailBundle:CRUD:email_template_edit.html.twig]]

    email.email_receipt:
        class: Librinfo\EmailBundle\Admin\EmailReceiptAdminConcrete
        arguments: [~, Librinfo\EmailBundle\Entity\EmailReceipt, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: EmailReceipt }

    email.email_link:
        class: Librinfo\EmailBundle\Admin\EmailLinkAdminConcrete
        arguments: [~, Librinfo\EmailBundle\Entity\EmailLink, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: EmailLink }
