librinfo_email:
    resource: "@LibrinfoEmailBundle/Resources/config/routing.yml"
    prefix:   /

librinfo_security:
    resource: "@LibrinfoSecurityBundle/Resources/config/routing.yml"
    prefix:   /

librinfo_base_entities:
    resource: "@LibrinfoBaseEntitiesBundle/Resources/config/routing.yml"
    prefix:   /

librinfo_doctrine:
    resource: "@LibrinfoDoctrineBundle/Resources/config/routing.yml"
    prefix:   /

librinfo_ui:
    resource: "@LibrinfoUIBundle/Resources/config/routing.yml"
    prefix:   /

librinfo_decorator:
    resource: "@LibrinfoDecoratorBundle/Resources/config/routing.yml"
    prefix:   /

librinfo_user:
    resource: "@LibrinfoUserBundle/Resources/config/routing.yml"
    prefix:   /

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /




