Librinfo\EmailBundle\Entity\EmailAttachment:
    type: entity
    fields:
        name:
            type: string
            nullable: true
        mimeType:
            type: string
            nullable: true
        size:
            type: float
            nullable: true
        file:
            type: text
            nullable: true
    manyToOne:
        email:
            targetEntity: Librinfo\EmailBundle\Entity\Email
            inversedBy: attachments
            joinColumn:
                name: email_id
            cascade: [ persist ]
